# Generated by Django 6.0.5 on 2026-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_permit__2d31f6_idx',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='permit_number',
            new_name='archive_number',
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['archive_number'], name='permits_rec_archive_258d09_idx'),
        ),
    ]
