# Generated by Django 6.0.5 on 2026-07-03 04:46

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_workflow_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_project_99e56a_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_baranga_92786b_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_year_4ca5d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_categor_a72c06_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='permits_rec_archive_258d09_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_record__721a4f_idx',
            old_name='permits_eng_record__type_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_project_cf687e_idx',
            old_name='permits_eng_proj_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_baranga_f2793d_idx',
            old_name='permits_eng_barangay_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_status_921cfe_idx',
            old_name='permits_eng_status_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_year_7fddfc_idx',
            old_name='permits_eng_year_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_title_e9dfed_idx',
            old_name='permits_eng_title_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringrecord',
            new_name='permits_eng_created_6a09c3_idx',
            old_name='permits_eng_created_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='record',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Permit Form', 'Permit Form'), ('Resolution', 'Resolution'), ('Inspection Report', 'Inspection Report'), ('Blueprint', 'Blueprint'), ('Picture', 'Picture'), ('Completion Report', 'Completion Report'), ('Acceptance Report', 'Acceptance Report'), ('Certificate', 'Certificate'), ('Program of Works', 'Program of Works'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='engineering_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.engineeringrecord'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permitdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
