# Generated by Django 6.0.5 on 2026-07-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Engineering Staff'), ('engineer', 'Municipal Engineer'), ('admin', 'Administrator')], default='staff', max_length=20),
        ),
    ]
