# Generated by Django 6.0.5 on 2026-07-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_type',
            field=models.CharField(choices=[('Road & Bridge', 'Road & Bridge'), ('Vertical Structure', 'Vertical Structure'), ('Flood Control', 'Flood Control'), ('Potable Water', 'Potable Water')], max_length=50),
        ),
    ]
