# Generated by Django 6.0.5 on 2026-07-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_document_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
