# Generated by Django 6.0.5 on 2026-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_requirementitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrequirement',
            name='is_waived',
            field=models.BooleanField(default=False),
        ),
    ]
