# Generated by Django 6.0.5 on 2026-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringrecord',
            name='illegal_compliance_status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Open / Unresolved'), ('pending_permit', 'Permit Application Filed'), ('resolved', 'Regularized / Complied')], default='unresolved', help_text='Compliance / regularization tracking for illegal construction.', max_length=20),
        ),
        migrations.AddField(
            model_name='engineeringrecord',
            name='is_illegal_construction',
            field=models.BooleanField(default=False, help_text='Flagged as illegal construction (constructed without building permit).'),
        ),
    ]
