# Generated by Django 6.0.5 on 2026-07-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_engineeringrecord_illegal_compliance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdetail',
            name='date_issued',
            field=models.DateField(blank=True, help_text='Date Building/Ancillary Permit was issued.', null=True),
        ),
    ]
