# Generated by Django 6.0.5 on 2026-07-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_permitdetail_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geocoded center latitude for Carigara barangay map pin', null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geocoded center longitude for Carigara barangay map pin', null=True),
        ),
        migrations.AddField(
            model_name='engineeringrecord',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geocoded latitude coordinate for map & Street View', null=True),
        ),
        migrations.AddField(
            model_name='engineeringrecord',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geocoded longitude coordinate for map & Street View', null=True),
        ),
    ]
