# Generated by Django 6.0.5 on 2026-07-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_barangay_latitude_barangay_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='permitdetail',
            name='permit_type',
            field=models.CharField(choices=[('Building', 'Building'), ('Electrical', 'Electrical'), ('Occupancy', 'Occupancy'), ('Fencing', 'Fencing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_type',
            field=models.CharField(choices=[('Road & Bridge', 'Road & Bridge'), ('Vertical Structure', 'Vertical Structure'), ('Flood Control', 'Flood Control'), ('Potable Water', 'Potable Water'), ('Building', 'Building'), ('Water System', 'Water System'), ('Drainage', 'Drainage'), ('Multi-purpose Hall', 'Multi-purpose Hall'), ('Others', 'Others')], max_length=50),
        ),
    ]
