# Generated by Django 6.0.5 on 2026-07-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_add_project_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='funding_source_other',
            field=models.CharField(blank=True, default='', help_text='Specified if Funding Source is Others', max_length=255),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent requirement item if this is a sub-document (e.g. Architectural Plan under Building Plan)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='permits.requirementitem'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('General Fund', 'General Fund'), ('20% Development Fund', '20% Development Fund'), ('LDRRM Fund', 'LDRRM Fund'), ('Trust Fund', 'Trust Fund'), ('National Government Fund', 'National Government Fund'), ('Provincial Government Fund', 'Provincial Government Fund'), ('DPWH', 'DPWH'), ('DILG', 'DILG'), ('DOH', 'DOH'), ('DepEd', 'DepEd'), ('Private', 'Private'), ('NGO', 'NGO'), ('Others', 'Others')], default='General Fund', max_length=255),
        ),
    ]
