# Generated by Django 6.0.5 on 2026-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_projectdetail_funding_source_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='is_group',
            field=models.BooleanField(default=False, help_text='True if this item is a parent container group holding child requirements (e.g. Building Plans).'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
