# Generated by Django 6.0.5 on 2026-08-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0015_requirementitem_is_group_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engineeringrecord',
            index=models.Index(fields=['record_type', 'status'], name='permits_eng_record__9c4428_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringrecord',
            index=models.Index(fields=['barangay', 'year'], name='permits_eng_baranga_fedbc9_idx'),
        ),
    ]
