# Generated by Django 6.0.5 on 2026-08-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0016_engineeringrecord_permits_eng_record__9c4428_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Engineering Office Head'), ('staff', 'Engineering Staff')], default='staff', max_length=20),
        ),
    ]
