# Generated by Django 6.0.5 on 2026-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='permits_doc_expiry__0ff11d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='permits_doc_uploade_6ae3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='permits_doc_documen_b011aa_idx'),
        ),
    ]
