# Generated by Django 6.0.5 on 2026-08-20 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_customuser_designation_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=128)),
                ('device_name', models.CharField(default='Unknown Device', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approval_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),

        migrations.AlterField(
            model_name='barangay',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geocoded reference latitude', null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geocoded reference longitude', null=True),
        ),
        migrations.AlterField(
            model_name='permitdetail',
            name='permit_type',
            field=models.CharField(choices=[('Building', 'Building'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Occupancy', 'Occupancy'), ('Fencing', 'Fencing'), ('Demolition', 'Demolition')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('General Fund', 'General Fund'), ('Barangay Fund', 'Barangay Fund'), ('20% Development Fund', '20% Development Fund'), ('LDRRM Fund', 'LDRRM Fund'), ('Trust Fund', 'Trust Fund'), ('National Government Fund', 'National Government Fund'), ('Provincial Government Fund', 'Provincial Government Fund'), ('DPWH', 'DPWH'), ('DILG', 'DILG'), ('DOH', 'DOH'), ('DepEd', 'DepEd'), ('Private', 'Private'), ('NGO', 'NGO'), ('Others', 'Others')], default='General Fund', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_token')},
        ),
    ]
