# Generated by Django 6.0.5 on 2026-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0024_systemfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeedback',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Engineering Office Admin'), ('staff', 'Engineering Staff')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('LGU General Fund', 'LGU General Fund'), ('Barangay Fund', 'Barangay Fund'), ('20% Development Fund', '20% Development Fund'), ('LDRRM Fund', 'LDRRM Fund'), ('Trust Fund', 'Trust Fund'), ('National Government Fund', 'National Government Fund'), ('Provincial Government Fund', 'Provincial Government Fund'), ('DPWH', 'DPWH'), ('DILG', 'DILG'), ('DOH', 'DOH'), ('DepEd', 'DepEd'), ('Private', 'Private'), ('NGO', 'NGO'), ('Others', 'Others')], default='LGU General Fund', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_status',
            field=models.CharField(choices=[('Completed', 'Completed')], default='Completed', max_length=20),
        ),
    ]
