# Generated by Django 6.0.5 on 2026-08-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0025_rename_permits_eng_is_ille_idx_permits_eng_is_ille_33d7d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
