# Generated by Django 6.0.5 on 2026-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0027_engineeringrecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdetail',
            name='permit_type',
            field=models.CharField(choices=[('Building', 'Building'), ('Electrical', 'Electrical'), ('Occupancy', 'Occupancy'), ('Fencing', 'Fencing')], max_length=30),
        ),
    ]
