# Generated by Django 6.0.5 on 2026-10-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0028_rename_permits_eng_is_ille_idx_permits_eng_is_ille_33d7d1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='permits.engineeringrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'unique_together': {('user', 'record')},
            },
        ),
        migrations.AddIndex(
            model_name='recordaccesslog',
            index=models.Index(fields=['user', '-accessed_at'], name='permits_rec_user_id_fe9f07_idx'),
        ),
        migrations.AddIndex(
            model_name='recordaccesslog',
            index=models.Index(fields=['record', '-accessed_at'], name='permits_rec_record__cc565a_idx'),
        ),
        migrations.AddIndex(
            model_name='recordaccesslog',
            index=models.Index(fields=['-accessed_at'], name='permits_rec_accesse_9e1cd3_idx'),
        ),
    ]
